# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Release

on:
  push:
    branches: [ main, next, next-major, beta, alpha ]
  pull_request:
    branches: '*'

jobs:
  quality:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x, 15.x]
        node-version: [16.x]
        # os: [ubuntu-latest, windows-latest]
        os: [ubuntu-latest]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: mskelton/setup-yarn@v1
    - name: Install dependencies
      run: yarn --frozen-lockfile
    # - run: yarn test

  publish:
    runs-on: ubuntu-latest
    # if: ${{ github.ref == 'refs/heads/main' }}
    needs: [quality]
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      id-token: write # to enable use of OIDC for npm provenance
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup yarn
      uses: mskelton/setup-yarn@v1
    - name: Install dependencies
      run: yarn --frozen-lockfile
    - name: Verify the integrity of provenance attestations and registry signatures for installed dependencies
      run: npm audit signatures
    - name: Release
      run: yarn semantic-release
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
